"""Схема модерации: user_moderation + mod_warnings.

Combot-style модерация, общая для бота и сайта. Бот — источник истины
(он реально банит/мьютит через Telegram), сайт делает аудируемые записи.

Таблицы (без внешних ключей, по соглашению проекта):

* ``user_moderation`` — текущее состояние ограничений игрока: до какого
  времени забанен/замьючен и сколько активных варнов. Одна строка на игрока
  (``user_id`` это PK). NULL в ``banned_until``/``muted_until`` = нет ограничения.
* ``mod_warnings`` — append-only история варнов: кто, кому, когда, почему,
  активен ли ещё (снятые/протухшие → active=false). Порог активных варнов
  триггерит авто-мьют.

Действия дублируются в ``audit_log`` (player.ban/unban/mute/unmute/warn/unwarn)
для ленты «кто что сделал» в админ-панели.

Revision ID: 0041_moderation
Revises: 0040_item_lifecycle
Create Date: 2026-06-16
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0041_moderation"
down_revision: Union[str, None] = "0040_item_lifecycle"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent (CREATE ... IF NOT EXISTS). On some prod DBs these tables were
    # created out-of-band before the migration history was repaired, so a plain
    # CREATE TABLE raises DuplicateTable and aborts the upgrade. IF NOT EXISTS
    # converges to the right shape whether or not the objects already exist;
    # on a clean DB every statement creates fresh. Each statement is executed
    # separately (asyncpg forbids multi-command prepared statements).
    statements = [
        # --- user_moderation: current restriction state, one row per player ---
        """
        CREATE TABLE IF NOT EXISTS user_moderation (
            user_id BIGINT NOT NULL PRIMARY KEY,
            banned_until TIMESTAMP WITH TIME ZONE,
            muted_until TIMESTAMP WITH TIME ZONE,
            warn_count INTEGER NOT NULL DEFAULT 0,
            ban_reason TEXT,
            mute_reason TEXT,
            tg_pending BOOLEAN NOT NULL DEFAULT false,
            updated_by BIGINT,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_user_moderation_banned_until ON user_moderation (banned_until)",
        "CREATE INDEX IF NOT EXISTS ix_user_moderation_muted_until ON user_moderation (muted_until)",
        "CREATE INDEX IF NOT EXISTS ix_user_moderation_tg_pending ON user_moderation (tg_pending) WHERE tg_pending",
        # --- mod_warnings: append-only warning history ---
        """
        CREATE TABLE IF NOT EXISTS mod_warnings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL,
            actor_user_id BIGINT,
            reason TEXT,
            active BOOLEAN NOT NULL DEFAULT true,
            expires_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_mod_warnings_user_active ON mod_warnings (user_id, active, created_at)",
    ]
    for stmt in statements:
        op.execute(stmt)


def downgrade() -> None:
    op.drop_index("ix_mod_warnings_user_active", table_name="mod_warnings")
    op.drop_table("mod_warnings")
    op.drop_index("ix_user_moderation_tg_pending", table_name="user_moderation")
    op.drop_index("ix_user_moderation_muted_until", table_name="user_moderation")
    op.drop_index("ix_user_moderation_banned_until", table_name="user_moderation")
    op.drop_table("user_moderation")
