"""Тёмный друн (AI-нарратор) + центральный поток событий мира.

Пять таблиц, всё append-only/конфиг, без внешних ключей (соглашение проекта):

* ``world_events`` — единый поток событий мира (дуэли, кейсы, ачивки, подарки,
  сезоны, браки, крупные выигрыши). Денормализованная проекция для ленты и
  нарратора; источник правды по деньгам/состоянию — прежние леджеры. Пишет
  ТОЛЬКО бот (Model 2).
* ``ai_settings`` — key→JSONB конфиг ИИ (base_url, api_key, model, temperature,
  enabled). Правится из админки без рестарта.
* ``ai_prompts`` — именованные промпты (persona/system/observation/...),
  редактируются в админке без деплоя.
* ``ai_messages`` — краткосрочная память: история запросов/ответов друна.
* ``ai_memories`` — долгосрочная память: факты об игроках/мире.

Идемпотентно (CREATE ... IF NOT EXISTS): на части прод-БД таблицы могли быть
созданы вне миграций. Каждый стейтмент выполняется отдельно (asyncpg запрещает
мультикомандные prepared statements).

Revision ID: 0045_ai_drun
Revises: 0044_feed_indexes
Create Date: 2026-06-17
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0045_ai_drun"
down_revision: Union[str, None] = "0044_feed_indexes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    statements = [
        # --- world_events: единый поток событий мира ---
        """
        CREATE TABLE IF NOT EXISTS world_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type VARCHAR(48) NOT NULL,
            actor_id BIGINT,
            target_id BIGINT,
            amount BIGINT,
            ref_table VARCHAR(32),
            ref_id BIGINT,
            severity SMALLINT NOT NULL DEFAULT 0,
            meta JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_world_events_created_at ON world_events (created_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_world_events_type_created ON world_events (type, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_world_events_actor_created ON world_events (actor_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_world_events_severity_created ON world_events (severity, created_at DESC)",
        # Идемпотентность бэкафилла/повторного emit: одна строка на исходную запись.
        "CREATE UNIQUE INDEX IF NOT EXISTS ux_world_events_ref ON world_events (ref_table, ref_id) WHERE ref_table IS NOT NULL",
        # --- ai_settings: конфиг ИИ (key→JSONB) ---
        """
        CREATE TABLE IF NOT EXISTS ai_settings (
            key VARCHAR(64) NOT NULL PRIMARY KEY,
            value JSONB NOT NULL,
            updated_by BIGINT,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        # --- ai_prompts: именованные промпты, редактируемые в админке ---
        """
        CREATE TABLE IF NOT EXISTS ai_prompts (
            name VARCHAR(64) NOT NULL PRIMARY KEY,
            body TEXT NOT NULL,
            description VARCHAR(512),
            enabled BOOLEAN NOT NULL DEFAULT true,
            updated_by BIGINT,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        # --- ai_messages: краткосрочная память (история диалога/постов) ---
        """
        CREATE TABLE IF NOT EXISTS ai_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            channel VARCHAR(32) NOT NULL DEFAULT 'chat',
            role VARCHAR(16) NOT NULL,
            content TEXT NOT NULL,
            user_id BIGINT,
            trigger_event_id BIGINT,
            tokens INTEGER,
            meta JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_ai_messages_channel_created ON ai_messages (channel, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_ai_messages_user_created ON ai_messages (user_id, created_at DESC)",
        # --- ai_memories: долгосрочная память (факты об игроках/мире) ---
        """
        CREATE TABLE IF NOT EXISTS ai_memories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            subject_id BIGINT,
            kind VARCHAR(32) NOT NULL DEFAULT 'fact',
            fact TEXT NOT NULL,
            weight SMALLINT NOT NULL DEFAULT 1,
            source VARCHAR(32),
            expires_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_ai_memories_subject ON ai_memories (subject_id, weight DESC)",
        "CREATE INDEX IF NOT EXISTS ix_ai_memories_kind ON ai_memories (kind, created_at DESC)",
    ]
    for stmt in statements:
        op.execute(stmt)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS ai_memories")
    op.execute("DROP TABLE IF EXISTS ai_messages")
    op.execute("DROP TABLE IF EXISTS ai_prompts")
    op.execute("DROP TABLE IF EXISTS ai_settings")
    op.execute("DROP TABLE IF EXISTS world_events")
