"""Тёмный друн: автономные ивенты + предложения владельцу (Phase 4 + Phase 6).

Две таблицы, append-only/состояние, без внешних ключей (соглашение проекта):

* ``drun_events`` — структурированная автономная активность друна: челленджи,
  прогнозы, мини-ивенты, временные цели. У ивента есть жизненный цикл
  (proposed→active→resolved→cancelled), участники (JSONB), награда, дедлайн и
  исход. Это даёт друну СОЗДАВАТЬ движ, а не только комментировать. Денежные
  выплаты по-прежнему идут через экономическое ядро бота (Model 2) — здесь
  только описание/состояние ивента.
* ``drun_proposals`` — очередь предложений действий для владельца (Phase 6):
  для высокоимпактных действий друн ПРЕДЛАГАЕТ, владелец подтверждает, система
  исполняет. Хранит сериализованный tool-вызов и статус
  (pending→approved→rejected→executed→expired).

Идемпотентно (CREATE ... IF NOT EXISTS). Каждый стейтмент отдельно (asyncpg
запрещает мультикомандные prepared statements).

Revision ID: 0052_drun_events
Revises: 0051_ai_memory_fastembed_384
Create Date: 2026-06-19
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0052_drun_events"
down_revision: Union[str, None] = "0051_ai_memory_fastembed_384"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    statements = [
        # --- drun_events: структурированная автономная активность ---
        """
        CREATE TABLE IF NOT EXISTS drun_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind VARCHAR(32) NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'proposed',
            title VARCHAR(256) NOT NULL,
            body TEXT NOT NULL DEFAULT '',
            created_by BIGINT,
            reward_kind VARCHAR(16),
            reward_amount BIGINT,
            participants JSONB NOT NULL DEFAULT '[]'::jsonb,
            outcome JSONB NOT NULL DEFAULT '{}'::jsonb,
            meta JSONB NOT NULL DEFAULT '{}'::jsonb,
            deadline_at TIMESTAMP WITH TIME ZONE,
            resolved_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_drun_events_status ON drun_events (status, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_drun_events_kind ON drun_events (kind, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS ix_drun_events_deadline ON drun_events (deadline_at) WHERE deadline_at IS NOT NULL",
        # --- drun_proposals: очередь предложений действий для владельца ---
        """
        CREATE TABLE IF NOT EXISTS drun_proposals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            status VARCHAR(16) NOT NULL DEFAULT 'pending',
            owner_id BIGINT,
            tool VARCHAR(48) NOT NULL,
            args JSONB NOT NULL DEFAULT '{}'::jsonb,
            rationale TEXT NOT NULL DEFAULT '',
            result JSONB NOT NULL DEFAULT '{}'::jsonb,
            decided_by BIGINT,
            decided_at TIMESTAMP WITH TIME ZONE,
            expires_at TIMESTAMP WITH TIME ZONE,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_drun_proposals_status ON drun_proposals (status, created_at DESC)",
    ]
    for stmt in statements:
        op.execute(stmt)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS drun_proposals")
    op.execute("DROP TABLE IF EXISTS drun_events")
