"""Drun raw chat archive for historical retrieval.

Revision ID: 0053_ai_chat_archive
Revises: 0052_drun_events
Create Date: 2026-06-21
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0053_ai_chat_archive"
down_revision: Union[str, None] = "0052_drun_events"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    statements = [
        """
        CREATE TABLE IF NOT EXISTS ai_chat_archive (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source VARCHAR(32) NOT NULL,
            source_message_id BIGINT NOT NULL,
            user_id BIGINT,
            name VARCHAR(96) NOT NULL DEFAULT '',
            text TEXT NOT NULL,
            message_at TIMESTAMP WITH TIME ZONE,
            meta JSONB NOT NULL DEFAULT '{}'::jsonb,
            embedding vector(384),
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            CONSTRAINT uq_ai_chat_archive_source_msg UNIQUE (source, source_message_id)
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_ai_chat_archive_user_time ON ai_chat_archive (user_id, message_at)",
        "CREATE INDEX IF NOT EXISTS ix_ai_chat_archive_source_time ON ai_chat_archive (source, message_at)",
        "CREATE INDEX IF NOT EXISTS ix_ai_chat_archive_embedding_hnsw ON ai_chat_archive USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL",
        """
        DO $$
        DECLARE
            has_russian boolean;
        BEGIN
            SELECT EXISTS(
                SELECT 1 FROM pg_ts_config WHERE cfgname = 'russian'
            ) INTO has_russian;

            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'ai_chat_archive' AND column_name = 'text_tsv'
            ) THEN
                IF has_russian THEN
                    EXECUTE 'ALTER TABLE ai_chat_archive ADD COLUMN text_tsv tsvector '
                            'GENERATED ALWAYS AS (to_tsvector(''russian'', coalesce(text, ''''))) STORED';
                ELSE
                    EXECUTE 'ALTER TABLE ai_chat_archive ADD COLUMN text_tsv tsvector '
                            'GENERATED ALWAYS AS (to_tsvector(''simple'', coalesce(text, ''''))) STORED';
                END IF;
            END IF;
        END$$;
        """,
        "CREATE INDEX IF NOT EXISTS ix_ai_chat_archive_text_tsv ON ai_chat_archive USING gin (text_tsv)",
    ]
    for stmt in statements:
        op.execute(stmt)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS ai_chat_archive")
