"""Person mention index mined from raw chat archive.

Revision ID: 0055_ai_person_mentions
Revises: 0054_ai_job_health
Create Date: 2026-06-22
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0055_ai_person_mentions"
down_revision: Union[str, None] = "0054_ai_job_health"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS ai_person_mentions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            archive_id BIGINT NOT NULL,
            source VARCHAR(32) NOT NULL,
            source_message_id BIGINT NOT NULL,
            mention VARCHAR(96) NOT NULL,
            mention_norm VARCHAR(96) NOT NULL,
            speaker_user_id BIGINT,
            speaker_name VARCHAR(96) NOT NULL DEFAULT '',
            text_excerpt TEXT NOT NULL DEFAULT '',
            message_at TIMESTAMP WITH TIME ZONE,
            confidence INTEGER NOT NULL DEFAULT 50,
            source_kind VARCHAR(32) NOT NULL DEFAULT 'regex',
            meta JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            CONSTRAINT uq_ai_person_mentions_archive_norm UNIQUE (archive_id, mention_norm)
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_ai_person_mentions_norm_time "
        "ON ai_person_mentions (mention_norm, message_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_ai_person_mentions_speaker "
        "ON ai_person_mentions (speaker_user_id, message_at)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS ai_person_mentions")
